const listaPalavras = [
    "casa", "carro", "gato", "cachorro", "banana", "computador", "mesa", "cadeira", "livro", "caneta", 
    "telefone", "janela", "porta", "copo", "água", "sol", "lua", "estrela", "terra", "fogo", "trevas", 
    "ar", "vento", "chuva", "neve", "pássaro", "peixe", "árvore", "flor", "grama", "pedra", "noob", 
    "rio", "mar", "oceano", "montanha", "vale", "deserto", "cidade", "vila", "pais", "continente", 
    "planeta", "universo", "amor", "felicidade", "tristeza", "alegria", "raiva", "medo", "roblox", 
    "coragem", "esperança", "paz", "guerra", "amizade", "inimizade", "família",  "magma", "one-piece", 
    "ódio", "trabalho", "escola", "férias", "feriado", "natal", "aniversário", "casamento", "divórcio", 
    "solteiro", "casado", "namorado", "namorada", "noivo", "noiva", "pai", "mãe", "filho", "filha", 
    "irmão", "irmã", "avô", "avó", "neto", "neta", "tio", "tia", "primo", "prima", "sobrinho", "clarão", 
    "sobrinha", "vizinho", "colega", "professor", "aluno", "médico", "enfermeiro", "advogado", "juiz", 
    "polícia", "ladrão", "herói", "vilão", "tempo", "espaço", "história", "presente", "passado", 
    "futuro", "memória", "sonho", "realidade", "fantasia", "verdade", "mentira", "segredo", "mistério", 
    "magia", "ciência", "tecnologia", "cultura", "arte", "música", "dança", "pintura", "escultura", 
    "literatura", "poesia", "prosa", "filosofia", "religião", "espiritualidade", "crença", "dúvida", 
    "certeza", "conhecimento", "ignorância", "sabedoria", "ignorância", "beleza", "feiura", "simplicidade", 
    "complexidade", "harmonia", "caos", "ordem", "liberdade", "prisão", "justiça", "injustiça", "igualdade", 
    "desigualdade", "riqueza", "pobreza", "sucesso", "fracasso", "desespero", "vitória", "derrota", "luz", 
    "covardia", "honra", "vergonha", "glória", "humilhação", "fama", "anonimato", "fortuna", "ganhou",
    "sorte", "azar", "saúde", "doença", "vida", "morte", "nascimento",  "luis-davi", "perdeu","apagão", 
    "dia", "noite", "amanhecer", "entardecer", "crepúsculo", "aurora", "madrugada", "meio-dia", "brilho", 
    "meia-noite", "calor", "frio", "inverno", "verão", "outono", "primavera", "solstício", "escuridão",
    "sombra"
  ];